# Generated by Django 4.2.7 on 2025-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_scientist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
