"""add processing_status to patient_metadata

Revision ID: f6ab3cf32c81
Revises: 4619c694edb3
Create Date: 2025-09-25 03:54:37.291577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ab3cf32c81'
down_revision: Union[str, Sequence[str], None] = '4619c694edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edf_files', sa.Column('session_name', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'edf_files', 'patient_metadata', ['patient_iid'], ['patient_iid'], ondelete='CASCADE')
    op.add_column('patient_metadata', sa.Column('processing_status', sa.String(length=30), server_default='new', nullable=False))
    op.add_column('trials', sa.Column('processing_status', sa.String(length=30), nullable=False))
    op.add_column('trials', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'updated_at')
    op.drop_column('trials', 'processing_status')
    op.drop_column('patient_metadata', 'processing_status')
    op.drop_constraint(None, 'edf_files', type_='foreignkey')
    op.drop_column('edf_files', 'session_name')
    # ### end Alembic commands ###
