# Generated by Django 4.2.7 on 2025-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
