# Generated by Django 4.2.7 on 2025-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0002_scientist_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
