# Generated by Django 4.2.7 on 2025-09-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scientists', '0003_alter_scientist_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('edf_file_id', models.UUIDField(blank=True, null=True)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('emotion_category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg_sessions', to=settings.AUTH_USER_MODEL)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_sessions', to='scientists.scientist')),
            ],
            options={
                'db_table': 'eeg_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['edf_file_id'], name='eeg_session_edf_fil_a1c23d_idx'), models.Index(fields=['scientist', 'status'], name='eeg_session_scienti_dfc65a_idx')],
            },
        ),
    ]
